version: '3'
services:      
  banco_blog:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=banco_blog
    ports: 
      - "5433:5432"

  springboot:
    build:
      dockerfile: ./docker/springboot.dockerfile
      context: .
    image: appspring
    container_name: appspring
    ports:
      - "8080:8080"
    depends_on:
      - "banco_blog"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=123456